name: Publish Website to CPanel
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.rrc-academyofaudit.com
          username: gukan@rrc-academyofaudit.com
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps